LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := FDroid
LOCAL_MODULE_TAGS := optional

LOCAL_REQUIRED_MODULES := FDroidPrivilegedExtension	

LOCAL_CERTIFICATE := PRESIGNED
LOCAL_SRC_FILES := FDroid.apk 
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)

include $(BUILD_PREBUILT)

include $(CLEAR_VARS)

LOCAL_MODULE := FDroidPrivilegedExtension
LOCAL_MODULE_TAGS := optional

# For sdk >= 26
#LOCAL_REQUIRED_MODULES := permissions_org.fdroid.fdroid.privileged.xml

LOCAL_CERTIFICATE := PRESIGNED
LOCAL_PRIVILEGED_MODULE := true
LOCAL_SRC_FILES := FDroidPrivilegedExtension.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)

include $(BUILD_PREBUILT)

#include $(CLEAR_VARS)
#
#LOCAL_MODULE := permissions_org.fdroid.fdroid.privileged.xml
#LOCAL_MODULE_CLASS := ETC
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/permissions
#LOCAL_SRC_FILES := $(LOCAL_MODULE)
#
#include $(BUILD_PREBUILT)
